### ISSUE TITLE
Problem with import, Qt5Agg error

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [alxdrcirilo/RamachanDraw#1]
Python 3.8.1 (default, Jan  6 2020, 10:49:15)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from RamachanDraw import fetch, phi_psi, plot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home-4/*****************/.local/lib/python3.8/site-packages/RamachanDraw/__init__.py", line 3, in <module>
    from RamachanDraw.plot_residues import plot
  File "/home-4/*****************/.local/lib/python3.8/site-packages/RamachanDraw/plot_residues.py", line 8, in <module>
    matplotlib.use('Qt5Agg')
  File "/home-4*****************/.local/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 307, in wrapper
    return func(*args, **kwargs)
  File "/home-4/*****************/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1307, in use
    switch_backend(name)
  File "/home-4/*****************/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 233, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'Qt5Agg' which requires the 'qt5' interactive framework, as 'headless' is currently running

**Comment by alxdrcirilo** [comment]
This error shows up when you do not have PyQt5 installed.
The plotting is dependent on the PyQt5 package since matplotlib is using the Qt5Agg backend.
To circumvent this, I switched the backend back to the default used by matplotlib.
You won't be needing PyQt5 installed henceforth.
